# General config file for project documentation parser

[paths]
dxf_path = "dxf/square_thick.dxf"
position_path = "POSITION.toml"
image_path = "image/triangle_no_dimensions.png"

[extractor]
type = "image"
