# General config file for project documentation parser

[hole]
    parser_type = "dxf"
    path = "dxf/two_rectangles_no_dimensions.dxf"
    position_path = "none"
    depth = [100, 50]
    hole = true

[dump]
    parser_type = "dxf"
    path = "dxf/two_rectangles_no_dimensions.dxf"
    position_path = "position.toml"
    depth = [0, 0]
    hole = false
