[gps]
polygon_coords = [
    [
        [-100.0, 0.0],
        [0.0, 0.0],
        [0.0, 100.0],
    ],
    [
        [200.0, -100.0],
        [300.0, -100.0],
        [300.0, 0.0],
    ]
]

[heightmap]
depth = [100, 50]
