[gps]
polygon_coords = [
    [
        [-100.0, 0.0],
        [0.0, 0.0],
        [0.0, 100.0],
    ],
    [
        [200.0, -100.0],
        [300.0, -100.0],
        [300.0, 0.0],
    ]
]

division_coords = [
    [
        [-100.0, 0.0],
        [-100.0, 25.0],
        [-100.0, 50.0],
        [-100.0, 75.0],
        [0.0, 100.0],
    ],
    [
        [200.0, -100.0],
        [200.0, -125.0],
        [200.0, -150.0],
        [200.0, -175.0],
        [300.0, -200.0],
    ]
]
